name: Docker Build

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'netbox_pdns/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docker.yml'
    tags:
      - 'v*'  # Always build on tags regardless of path changes
  pull_request:
    branches:
      - main
    paths:
      - 'netbox_pdns/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docker.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
            # branch event
            type=ref,event=branch
            # PR event  
            type=ref,event=pr
            # set edge tag for develop branch
            type=raw,value=edge,enable=${{ github.ref == 'refs/heads/develop' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
